<<<<<<< HEAD
version: "3"
=======
>>>>>>> 0af4aecf50426fc1e35696ca4c47940737175b26
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
<<<<<<< HEAD
=======
    environment:
      - JEKYLL_ENV=development
>>>>>>> 0af4aecf50426fc1e35696ca4c47940737175b26
